// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEkvI7_uxPi03bO78K4rZ8fPMcIokYRQA',
    appId: '1:967698205989:web:d8ae1335095a29ad121ecc',
    messagingSenderId: '967698205989',
    projectId: 'culture-loop',
    authDomain: 'culture-loop.firebaseapp.com',
    storageBucket: 'culture-loop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJsj60g9m1fA_Yj_xSAxWdKkTPJkK170',
    appId: '1:967698205989:android:4508e36e32c5dfb0121ecc',
    messagingSenderId: '967698205989',
    projectId: 'culture-loop',
    storageBucket: 'culture-loop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1v6pbfoWw1QT0oFk9M5J8e40XOfQ0SU',
    appId: '1:967698205989:ios:ea14554dfb158862121ecc',
    messagingSenderId: '967698205989',
    projectId: 'culture-loop',
    storageBucket: 'culture-loop.firebasestorage.app',
    iosBundleId: 'com.example.cultureloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1v6pbfoWw1QT0oFk9M5J8e40XOfQ0SU',
    appId: '1:967698205989:ios:ea14554dfb158862121ecc',
    messagingSenderId: '967698205989',
    projectId: 'culture-loop',
    storageBucket: 'culture-loop.firebasestorage.app',
    iosBundleId: 'com.example.cultureloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEkvI7_uxPi03bO78K4rZ8fPMcIokYRQA',
    appId: '1:967698205989:web:4771ed1dba8a59a7121ecc',
    messagingSenderId: '967698205989',
    projectId: 'culture-loop',
    authDomain: 'culture-loop.firebaseapp.com',
    storageBucket: 'culture-loop.firebasestorage.app',
  );

}